<?php
/**
 * Created by PhpStorm.
 * User: administarot
 * Date: 2018/9/1
 * Time: 10:17
 */

namespace app\admin\controller;

use think\Controller;
use app\admin\model\ContactModel as ContactModel;



class ContactController extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //编辑联系我们 页面
    public function get_contact_edit()
    {
        try{
            //判断过期时间
            $this->session_end();
            //判断登陆状态
            if (!session('?admin_dengluming')) {
                return redirect('/admin/login');
            }
//            $data = input();//通过助手将POST所有数据交给 data
            $contact = new ContactModel();
            $data = $contact->find();
//        $sql="select * from base_production where pe_id='".$data['id']."'";
//        $result=Db::query($sql);
//            $j['id']=$data['id'];
//            $j['page']=$data['page'];
//            $j['imgpath']=config("production_upload_path");
//            $j["sidebar"] = 15;

            $this->assign('data',$data);
//            return view('production_edit',$j);
        }catch (\Exception $e){
            $this->error('执行错误');
        }
        $j["sidebar"] = 5;
        return $this->fetch('contact_edit',$j);
    }

    //编辑生产环境 提交处理
    public function post_contact_edit()
    {
        try{
            //判断过期时间
            $this->session_end();
            //判断登陆状态
            if (!session('?admin_dengluming')) {
                return redirect('/admin/login');
            }
            $data = input('post.');//通过助手将POST所有数据交给 data

            // 获取表单上传文件 例如上传了001.jpg
            $imgUp=0;

            $imgname = "";
            // 移动到框架应用根目录/static/uploads/banner/ 目录下
            $data['cu_company']=addslashes($data['cu_company']);
            $data['cu_name']=addslashes($data['cu_name']);
            $data['cu_email']=addslashes($data['cu_email']);
            $data['cu_seat']=addslashes($data['cu_seat']);
            $data['cu_phone']=addslashes($data['cu_phone']);
            $data['cu_access']=addslashes($data['cu_access']);
            $data['cu_chuanzhen']=addslashes($data['cu_chuanzhen']);
            $contact = new ContactModel();
            $data = $contact->where('cu_id',$data['id'])->update([
                'cu_company'=>$data['cu_company'],
                'cu_name' => $data['cu_name'],
                'cu_email' => $data['cu_email'],
                'cu_seat' =>  $data['cu_seat'],
                'cu_phone' =>  $data['cu_phone'],
                'cu_access' =>  $data['cu_access'],
                'cu_chuanzhen' => $data['cu_chuanzhen']
            ]);
//            $sql="update base_production set pe_title='".$data['pe_title']."',
//            pe_order='".$data['pe_order']."' where pe_id='".$data['id']."'";

//        Db::execute($sql);

//            $tiaozhuanlujing="/admin/contactEdit";
//            return redirect($tiaozhuanlujing);
        }catch (\Exception $e){
            return show('200','保存失败,请联系管理员！');
        }
        return show('200','保存成功！');
    }
}