<?php
namespace app\index\controller;
use app\index\mode\Index as indexmode;
use app\admin\model\ContactModel;
use app\admin\model\BannerModel;
use think\Db;
use think\Controller;

class IndexController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        try{
            //查询banner
            $banner = new BannerModel();
            $banner_data = $banner->order('bn_order','desc')->select();
            //查询联系我们
            $contact = new ContactModel();
            $contact_data = $contact->find();
            $this->assign('banner_data',$banner_data);
            $this->assign('contact_data',$contact_data); //联系我们
        }catch (\Exception $e){
            $this->error($e->getMessage());
        }
    }

    public function index()
    {
        $j = array();
        try{
            //查询新闻
            $sql_new="select * from base_news order by ns_id desc LIMIT 3";
            $j['news']=Db::query($sql_new);
            //查询产品展示
            $sql_product = "select * from base_product ORDER BY pd_order DESC";
            $product = Db::query($sql_product);
            //查询生产环境
            $sql_production = "select * from base_production ORDER BY pe_order DESC";
            $production = Db::query($sql_production);
            $this->assign('product',$product);//产品展示
            $this->assign('production',$production);//生产环境
            $j['imgpath']=config("product_upload_path");
            $j['imgpath_production']=config("production_upload_path");
            $j['imgpath_news']=config("news_upload_path");//新闻资讯

        }catch (\Exception $e){
            $this->error($e->getMessage());
        }

      return view('index',$j);
    }

    public function news_list()
    {
        try{
            $index = new indexmode();
            //查询banner
            $list = $index->get_banner();
            //查询新闻
            $news = Db::name('news')->order('ns_intime','desc')->paginate(8);

            $this->assign('list',$list);
            $this->assign('news',$news);
        }catch (\Exception $e){
            $this->error($e->getMessage());
        }
        return $this->fetch('news_list');
    }

    public function news()
    {
      $index = new indexmode();
        $id = request()->param()['page'];
        //查询banner
        $list = $index->get_banner();
        //查询新闻
      $news = $index->get_news_info($id);
        $this->assign('list',$list);
        $this->assign('news',$news);

//        return view('news',$stat);
        return $this->fetch('news');
    }

    public function miss()
    {
        return view('miss');
    }

}
